(fix) allow port 1080 for SOCKS5 connections
HDInnovations/UNIT3D-Community-Edition pull request #3884
Opened 2024-05-28 18:11 UTC by bersLucas

Ports in the blacklist or ports below 1024 are blocked, but if a user is using a SOCKS5, the connection will go through port 1080 and they will see the "Illegal port" error message.

This PR allows 1080 specifically

2024-05-29 00:15 UTC, Roardom requested changes
`$queries['port'] !== 1080` is always false because `$queries['port']` is a string.

Also, `$queries['port'] < 1024 && $queries['port'] != 1080` and `$queries['port'] < 1024` are logically equivalent.

2024-05-29 13:05 UTC, bersLucas commented
> `$queries['port'] !== 1080` is always true because `$queries['port']` is a string.
> 
> Also, `$queries['port'] < 1024 && $queries['port'] != 1080` and `$queries['port'] < 1024` are logically equivalent.

But 1080 is greater than 1024, should a whitelist be used instead?

2024-05-29 16:40 UTC, bersLucas commented
Added changed. My apologies as I am a little new to PHP

2024-05-29 18:25 UTC, HDVinnie commented
> > `$queries['port'] !== 1080` is always true because `$queries['port']` is a string.
> 
> > 
> 
> > Also, `$queries['port'] < 1024 && $queries['port'] != 1080` and `$queries['port'] < 1024` are logically equivalent.
> 
> 
> 
> But 1080 is greater than 1024, should a whitelist be used instead?

The logic is a less than sign not greater than.

2024-05-29 19:48 UTC, bersLucas commented
![Screenshot 2024-05-29 154738](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/3892772/432f3d36-29bb-4d20-85ae-3ebbcf12464f)

That's interesting. My message is "illegal port 1". Could this mean anything?

2024-05-29 19:50 UTC, bersLucas commented
Related: https://github.com/qbittorrent/qBittorrent/issues/18472

2024-05-29 20:44 UTC, HDVinnie commented
Yes it says right in message your client is using port 1. This is a client bug. Not UNIT3D.

2024-05-29 20:45 UTC, closed without merging

2024-05-29 20:50 UTC, bersLucas commented
Since Libtorrent is intentionally sending 1, can this ever be supported in Unit3d or is this a lost cause?

2024-05-29 20:52 UTC, HDVinnie commented
I'll discuss it over with the team and let you know. As for now this pull request is closed as the logic didn't make sense and it was against master branch instead of v8.x.x as described in contributing guide.

2024-05-30 05:03 UTC, Roardom commented
> [...]
> 
> That's interesting. My message is "illegal port 1". Could this mean anything?

If you want to allow libtorrent-based socks5, you have to do `!== '1'`, not `!== '1080'`.

UNIT3D is designed to incentivize a strong seedbase, such as:

- Offering bonus points for seeders
- Offering permanent freeleech if you have seeded 10TiB for an average of 60 days
- Displays to other users the status of your connectivity in the peerlist

It is not the goal of UNIT3D to encourage misuse of p2p protocols. BitTorrent is designed for peer to peer usage. This means that all users should be connectable. Users refusing to be connectable is against the very intention of peer to peer communication. There are many alternative non-peer-to-peer methods of data transfer that you could use instead if you prefer to not be connectable: web server, ftp server, etc.

2025-02-16 00:25 UTC, wgomg commented
I don't mean to necrobump but has there been further discussion on this?

2025-02-16 02:27 UTC, Roardom commented
> I don't mean to necrobump but has there been further discussion on this?

The stance has remained firm. Since this PR, the tracker now has the option to not provide peer lists to unconnectable users, as well as not provide bonus points for unconnectable peers.