(Add) Allow internal options for internals in non-internal group
HDInnovations/UNIT3D-Community-Edition pull request #4370
Opened 2024-12-08 13:14 UTC by Obi-Wana

Internals that are not member of the internal group (e.g., Editor) and not Moderator+ should still be able to set the internal options on their uploads. They need to be in at least one Internal group, checked using count of `InternalUsers`.

2024-12-08 14:46 UTC, Roardom requested changes
Great idea!

Can we use `$user->internals()->exists()` instead to make it more efficient?

Further, I think we can even drop the `is_internal` column on the `groups` table and use this relation as the source of truth instead for all cases the `is_internal` flag is checked. What do you think @HDVinnie?

2024-12-08 22:01 UTC, Obi-Wana commented
> Can we use `$user->internals()->exists()` instead to make it more efficient?

No, `->exists()` does not exist on this, just checked.


> Further, I think we can even drop the `is_internal` column on the `groups` table and use this relation as the source of truth instead for all cases the `is_internal` flag is checked. What do you think @HDVinnie?

I'll let this up to you, and think it should be going into its own PR.

2024-12-08 22:05 UTC, HDVinnie commented
LGTM. Just swap the count for exist.

2024-12-09 20:44 UTC, HDVinnie approved these changes

2024-12-09 21:14 UTC, Roardom requested changes
When using `loadExists`, you need to specify the relation to load, i.e. `->loadExists('internals')`. Then, instead of checking for if `$user->internals()->exists(), you only have to check the `$user->internals_exists` property that's added to the user without needing further database calls.

2024-12-20 15:41 UTC, Obi-Wana commented
> When using `loadExists`, you need to specify the relation to load, i.e. `->loadExists('internals')`. Then, instead of checking for if `$user->internals()->exists()`, you only have to check the `$user->internals_exists` property that's added to the user without needing further database calls.

Added this to the APIController, but Larastan doesn't seem to like it...

2024-12-21 11:27 UTC, Roardom commented
I checked through the larastan repo and you're right: unfortunately larastan doesn't yet support relation_exists (although it does support relation_count).

Try adding `/** @phpstan-ignore property.notFound (Larastan doesn't yet support loadExists())` wherever the property is accessed.
Relevant documentation can be found here: https://phpstan.org/user-guide/ignoring-errors

2024-12-30 04:59 UTC, Roardom requested changes

2024-12-30 04:59 UTC, Roardom commented on app/Http/Requests/StoreTorrentRequest.php
> +        $user = $request->user();
Can `->loadExists('internals')` and `->internals_exists` be used here as well?

2024-12-30 04:59 UTC, Roardom commented on resources/views/torrent/create.blade.php
Can `->loadExists('internals')` and `->internals_exists` be used here as well (Inside `TorrentController::update()` at the bottom of the function)

2025-01-02 13:26 UTC, Obi-Wana commented on resources/views/torrent/create.blade.php
As far as I can tell, we'd need to change all `auth()->user()...` to use `$request->user()->loadExists...` from the `TorrentController::update()` function.

2025-01-02 13:43 UTC, Obi-Wana commented on app/Http/Requests/StoreTorrentRequest.php
> +        $user = $request->user();
Added.

2025-01-09 06:33 UTC, Roardom commented on resources/views/torrent/create.blade.php
Oops, sorry. I meant `TorrentController::create()`:

```php
            'user'         => $request->user()->loadExists('internals'),
```

However, that made me look again and realize you probably want to also add the same logic to `TorrentController::edit()` and `torrent/edit.blade.php`

2025-01-24 13:20 UTC, Roardom requested changes
Can you do a ctrl+f in your IDE for `->group->is_internal` and replace all the instances with the `->internals()->exists()` logic? (And use eager loading if the query is used multiple times in a single http request).

Thanks!

2025-02-20 16:21 UTC, Roardom approved these changes

2025-02-27 14:11 UTC, merged

2025-02-28 06:16 UTC, Roardom commented
Thank you!